#!/bin/bash

# echo -e '#!/bin/bash\n [command]' > [filename] && chmod u+x [filename]

echo -e '#!/bin/bash\nls -l' > 3-listfiles  && chmod u+x 3-listfiles

echo -e '#!/bin/bash\nls -la' > 4-listmorefiles  && chmod u+x 4-listmorefiles

echo -e '#!/bin/bash\nls -nla' > 5-listfilesdigitonly && chmod u+x 5-listfilesdigitonly

echo -e '#!/bin/bash\nmkdir /tmp/my_first_directory' > 6-firstdirectory && chmod u+x 6-firstdirectory

echo -e '#!/bin/bash\nmv /tmp/betty /tmp/my_first_directory/' > 7-movethatfile && chmod u+x 7-movethatfile

echo -e '#!/bin/bash\nrm /tmp/my_first_directory/betty' > 8-firstdelete && chmod u+x 8-firstdelete

echo -e '#!/bin/bash\nrmdir /tmp/my_first_directory' > 9-firstdirdeletion && chmod u+x 9-firstdirdeletion

echo -e '#!/bin/bash\ncd -' > 10-back && chmod u+x 10-back

#echo -e '#!/bin/bash\n' > 11-lists && chmod u+x 11-lists

#echo -e '#!/bin/bash\n [command]' > 12-file_type && chmod u+x 12-file_type

#echo -e '#!/bin/bash\n [command]' > 13-symbolic_link && chmod u+x 13-symbolic_link

#echo -e '#!/bin/bash\n [command]' > 14-copy_html && chmod u+x 14-copy_html

#echo -e '#!/bin/bash\n [command]' > 15-lets_move && chmod u+x 15-lets_move

#echo -e '#!/bin/bash\n [command]' > 16-clean_emacs && chmod u+x 16-clean_emacs

#echo -e '#!/bin/bash\n [command]' > 17-tree && chmod u+x 17-tree
